### ISSUE TITLE
Crash when searching in the settings (1.19.2, InventoryProfilesNext)

### ISSUE THREAD

**Issue by SiverDX** [blackd/libIPN#11]
relevant mods:
* kotlinforforge-3.11.0-all.jar
* libIPN-forge-1.19.2.0.6.jar
* InventoryProfilesNext-forge-1.19-1.9.7.jar

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-04-29 20:18:31
Description: Rendering screen

java.lang.NoClassDefFoundError: ca/solostudios/fuzzykt/FuzzyKt
	at org.anti_ad.mc.common.extensions.StringKt.fuzzMatch(string.kt:88) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ConfigListWidget$ConfigOptionEntry.getDontDrawOverlay(ConfigListWidget.kt:111) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ConfigListWidget$ConfigOptionEntry.disabled(ConfigListWidget.kt:143) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.disabled(Widget.kt:150) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.disabled(Widget.kt:150) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.contains(Widget.kt:126) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ButtonWidget.render(ButtonWidget.kt:69) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.renderChildren(Widget.kt:463) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.render(Widget.kt:451) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidget$DefaultImpls.render(Widget.kt:156) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.render(Widget.kt:45) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ConfigWidgetBase.render(ConfigWidgetsCommon.kt:61) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ConfigKeyToggleBooleanWidget.render(ConfigWidgetsMore.kt:201) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.renderChildren(Widget.kt:463) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.render(Widget.kt:451) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidget$DefaultImpls.render(Widget.kt:156) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.render(Widget.kt:45) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ConfigListWidget$ConfigOptionEntry.render(ConfigListWidget.kt:150) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.renderChildren(Widget.kt:463) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.render(Widget.kt:451) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidget$DefaultImpls.render(Widget.kt:156) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.render(Widget.kt:45) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ScrollableContainerWidget$_contentContainer$1.superRender(ScrollableContainerWidget.kt:66) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ScrollableContainerWidget$contentCustomRendererDefault$1.invoke(ScrollableContainerWidget.kt:93) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ScrollableContainerWidget$contentCustomRendererDefault$1.invoke(ScrollableContainerWidget.kt:92) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ScrollableContainerWidget$_contentContainer$1.render(ScrollableContainerWidget.kt:58) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.renderChildren(Widget.kt:463) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.render(Widget.kt:446) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidget$DefaultImpls.render(Widget.kt:156) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.render(Widget.kt:45) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ScrollableContainerWidget.render(ScrollableContainerWidget.kt:188) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.renderChildren(Widget.kt:463) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.render(Widget.kt:451) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidget$DefaultImpls.render(Widget.kt:156) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.render(Widget.kt:45) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.AnchoredListWidget.render(AnchoredListWidget.kt:73) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.ConfigListWidget.render(ConfigListWidget.kt:65) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.renderChildren(Widget.kt:463) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidgetRenderer$DefaultImpls.render(Widget.kt:451) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.IWidget$DefaultImpls.render(Widget.kt:156) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.widgets.Widget.render(Widget.kt:45) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.screen.BaseScreen.render(BaseScreen.kt:105) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.screen.ConfigScreenBase.render(ConfigScreenBase.kt:171) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at org.anti_ad.mc.common.gui.screen.BaseScreen.m_6305_(BaseScreen.kt:116) ~[libIPN-forge-1.19-2.0.6.jar%23581!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441) ~[forge-1.19.2-43.2.8-universal.jar%23710!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434) ~[forge-1.19.2-43.2.8-universal.jar%23710!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23705!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23705!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23705!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23705!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23705!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.8.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.ClassNotFoundException: ca.solostudios.fuzzykt.FuzzyKt
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 64 more
```

**Comment by blackd** [comment]
meh the forge build didn't pack all the classes. Will have an update soon.
