### ISSUE TITLE
breaks in 1.18.2

### ISSUE THREAD

**Issue by Gilithrimm** [blackd/libIPN#6]
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'libIPN' (libipn) 1.0.3 with version 1.0.3 or later that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'libIPN' (libipn) 1.0.3 requires any version between 1.18-beta.1 (inclusive) and 1.18.2 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:213)
	at crystallauncher.MineClient.main(MineClient.java:36)
```

**Comment by blackd** [comment]
there is a special version for 1.18.2
https://www.curseforge.com/minecraft/mc-mods/libipn/files/4028715
