### ISSUE TITLE
crashes when I use search in crafting menu: Unreported exception thrown! java.util.NoSuchElementException: null 

### ISSUE THREAD

**Issue by inikishev** [blackd/libIPN#9]
https://gist.github.com/stunlocked1/7c780df231b378a199c12a74fbcad698
```
java.util.NoSuchElementException: null
	at java.util.ArrayDeque.getLast(ArrayDeque.java:413) ~[?:?]
	at net.minecraft.class_4587.method_23760(class_4587.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25297(class_332.java:255) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25293(class_332.java:239) ~[client-intermediary.jar:?]
	at org.anti_ad.mc.common.vanilla.render.TextureKt.vanilla_rBlit(Texture.kt:92) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.TextureKt.internal_rDrawSprite(Texture.kt:124) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.TextureKt.rDrawCenteredSprite(Texture.kt:96) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.TextureKt.rDrawCenteredSprite(Texture.kt:85) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.drawHotSprite(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.4.jar:?]
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.postRenderHud(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.4.jar:?]
	at net.minecraft.class_329.handler$bcb000$inventoryprofilesnext$postRenderHotbar(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1759(class_329.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.mixinextras$bridge$13$method_1759(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.wrapOperation$bbf000$immediatelyfast$if$Batching(class_329.java:1474) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:200) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:918) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by blackd** [comment]
I cant recreate this.
can you export a modpack and post it here

**Comment by blackd** [comment]
closing due to inactivity
